### ISSUE TITLE
GRPO训练Qwen2.5Omni异常

### ISSUE THREAD

**Issue by Paipaier** [modelscope/ms-swift#4499]
![Image](https://github.com/user-attachments/assets/68b0eba3-68df-48fb-a682-3b9df728724b)
使用GRPO训练qwen2.5omni模型，训练后模型保存的ckpt size和之前不对应，导致无法加载推理
MAX_PIXELS=1003520 \
NPROC_PER_NODE=8 \
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
swift rlhf \
    --rlhf_type grpo \
    --model $MDOEL_PATH \
    --reward_funcs external_segments_reward \
    --reward_weights 1 \
    --train_type full \
    --lora_rank 8 \
    --lora_alpha 32 \
    --target_modules all-linear \
    --torch_dtype bfloat16 \
    --dataset $DATA_PATH \
    --external_plugins   \
    --max_completion_length 1024 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 2 \
    --learning_rate 5e-7 \
    --gradient_accumulation_steps 2 \
    --eval_steps 100 \
    --save_steps 1000 \
    --save_total_limit 2 \
    --logging_steps 5 \
    --max_length 8192 \
    --output_dir  o \
    --warmup_ratio 0.05 \
    --dataloader_num_workers 4 \
    --dataset_num_proc 4 \
    --num_generations 8 \
    --temperature 1.0 \
    --top_p 0.99 \
    --top_k 50 \
    --system ' ' \
    --deepspeed zero2 \
    --log_completions true \
    --report_to wandb \
    --freeze_vit false \
    --freeze_aligner false \
    --save_only_model true

**Comment by hjh0119** [comment]
what's the version of transformers?

**Comment by Paipaier** [comment]
> what's the version of transformers?

transformers 是 4.52.3
ms-swift 是 3.5.0.dev0

**Comment by hjh0119** [comment]
let me try to reproduce it on my side

**Comment by Paipaier** [comment]
ok, thanks
I have a issue before, it seems like 
https://github.com/modelscope/ms-swift/issues/4495
AttributeError: 'qwen2.5omnixxxx' object has no attribute 'model'

![Image](https://github.com/user-attachments/assets/17294354-0046-4735-837d-0d85c4cf4eeb)
I made modifications here to solve the problem, I don't know if it's because of this

**Comment by hjh0119** [comment]
> AttributeError: 'qwen2.5omnixxxx' object has no attribute 'model'

the issue has been fixed in https://github.com/modelscope/ms-swift/pull/4468

**Comment by Paipaier** [comment]
> > AttributeError: 'qwen2.5omnixxxx' object has no attribute 'model'
> 
> the issue has been fixed in [#4468](https://github.com/modelscope/ms-swift/pull/4468)

ok, let me have a try 😄

**Comment by Paipaier** [comment]
https://github.com/hiyouga/LLaMA-Factory/pull/7537
I have found a solution, it seems that the training only saved Thinkers and needs to be merged. [thinker + talker] -> [omni]
Thank you for your help. Maybe you can add it to the next version

**Comment by Paipaier** [comment]
It seems that there is still a problem. The inference result in completions.json during training is normal. Although it can be inferred after merging, the inference result is abnormal.

![Image](https://github.com/user-attachments/assets/b7decf08-67a4-4d35-b4c3-0872a652d55b)
